2024-04-24 09:22:02,769 INFO    MainThread:44204 [wandb_setup.py:_flush():76] Current SDK version is 0.16.6
2024-04-24 09:22:02,771 INFO    MainThread:44204 [wandb_setup.py:_flush():76] Configure stats pid to 44204
2024-04-24 09:22:02,771 INFO    MainThread:44204 [wandb_setup.py:_flush():76] Loading settings from C:\Users\lukea\.config\wandb\settings
2024-04-24 09:22:02,772 INFO    MainThread:44204 [wandb_setup.py:_flush():76] Loading settings from G:\My Drive\MSc\0_Project\MSc_Project\wandb\settings
2024-04-24 09:22:02,772 INFO    MainThread:44204 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-04-24 09:22:02,772 INFO    MainThread:44204 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-04-24 09:22:02,773 INFO    MainThread:44204 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'main.py', 'program_abspath': 'g:\\my drive\\msc\\0_project\\msc_project\\main.py', 'program': 'g:\\my drive\\msc\\0_project\\msc_project\\main.py'}
2024-04-24 09:22:02,773 INFO    MainThread:44204 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-04-24 09:22:02,774 INFO    MainThread:44204 [wandb_init.py:_log_setup():521] Logging user logs to G:\My Drive\MSc\0_Project\MSc_Project\wandb\run-20240424_092202-ue9ikutd\logs\debug.log
2024-04-24 09:22:02,774 INFO    MainThread:44204 [wandb_init.py:_log_setup():522] Logging internal logs to G:\My Drive\MSc\0_Project\MSc_Project\wandb\run-20240424_092202-ue9ikutd\logs\debug-internal.log
2024-04-24 09:22:02,774 INFO    MainThread:44204 [wandb_init.py:init():561] calling init triggers
2024-04-24 09:22:02,775 INFO    MainThread:44204 [wandb_init.py:init():568] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.001, 'architecture': 'SCAE', 'dataset': 'MNIST', 'epochs': 3, 'batch size': 64, 'v_th': 1, 'tau_m': 24. * msecond}
2024-04-24 09:22:02,775 INFO    MainThread:44204 [wandb_init.py:init():611] starting backend
2024-04-24 09:22:02,775 INFO    MainThread:44204 [wandb_init.py:init():615] setting up manager
2024-04-24 09:22:02,781 INFO    MainThread:44204 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-04-24 09:22:02,784 INFO    MainThread:44204 [wandb_init.py:init():623] backend started and connected
2024-04-24 09:22:02,798 INFO    MainThread:44204 [wandb_init.py:init():715] updated telemetry
2024-04-24 09:22:02,910 INFO    MainThread:44204 [wandb_init.py:init():748] communicating run to backend with 90.0 second timeout
2024-04-24 09:22:03,666 INFO    MainThread:44204 [wandb_run.py:_on_init():2357] communicating current version
2024-04-24 09:22:04,111 INFO    MainThread:44204 [wandb_run.py:_on_init():2366] got version response 
2024-04-24 09:22:04,111 INFO    MainThread:44204 [wandb_init.py:init():799] starting run threads in backend
2024-04-24 09:22:04,823 INFO    MainThread:44204 [wandb_run.py:_console_start():2335] atexit reg
2024-04-24 09:22:04,825 INFO    MainThread:44204 [wandb_run.py:_redirect():2190] redirect: wrap_raw
2024-04-24 09:22:04,825 INFO    MainThread:44204 [wandb_run.py:_redirect():2255] Wrapping output streams.
2024-04-24 09:22:04,826 INFO    MainThread:44204 [wandb_run.py:_redirect():2280] Redirects installed.
2024-04-24 09:22:04,827 INFO    MainThread:44204 [wandb_init.py:init():842] run started, returning control to user process
2024-04-24 12:30:58,065 ERROR   MainThread:44204 [util.py:get_module():270] Error importing optional module plotly.tools
Traceback (most recent call last):
  File "C:\Users\lukea\anaconda3\envs\diss\Lib\site-packages\wandb\util.py", line 236, in import_module_lazy
    return sys.modules[name]
           ~~~~~~~~~~~^^^^^^
KeyError: 'plotly.tools'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lukea\anaconda3\envs\diss\Lib\site-packages\wandb\util.py", line 265, in get_module
    return import_module_lazy(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lukea\anaconda3\envs\diss\Lib\site-packages\wandb\util.py", line 238, in import_module_lazy
    spec = importlib.util.find_spec(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lukea\anaconda3\envs\diss\Lib\importlib\util.py", line 91, in find_spec
    parent = __import__(parent_name, fromlist=['__path__'])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'plotly'
2024-04-24 12:44:12,214 INFO    MainThread:44204 [wandb_run.py:_finish():2064] finishing run llalderson/MSc Project/ue9ikutd
2024-04-24 12:44:12,214 INFO    MainThread:44204 [wandb_run.py:_atexit_cleanup():2304] got exitcode: 0
2024-04-24 12:44:12,214 INFO    MainThread:44204 [wandb_run.py:_restore():2287] restore
2024-04-24 12:44:12,215 INFO    MainThread:44204 [wandb_run.py:_restore():2293] restore done
2024-04-24 12:44:24,385 INFO    MainThread:44204 [wandb_run.py:_footer_history_summary_info():3936] rendering history
2024-04-24 12:44:24,386 INFO    MainThread:44204 [wandb_run.py:_footer_history_summary_info():3968] rendering summary
2024-04-24 12:44:24,408 INFO    MainThread:44204 [wandb_run.py:_footer_sync_info():3895] logging synced files
