2024-05-29 17:57:17,276 INFO    StreamThr :8512 [internal.py:wandb_internal():86] W&B internal server running at pid: 8512, started at: 2024-05-29 17:57:17.273602
2024-05-29 17:57:17,280 DEBUG   HandlerThread:8512 [handler.py:handle_request():146] handle_request: status
2024-05-29 17:57:17,300 INFO    WriterThread:8512 [datastore.py:open_for_write():87] open: G:\My Drive\MSc\0_Project\MSc_Project\wandb\run-20240529_175717-zgh6omna\run-zgh6omna.wandb
2024-05-29 17:57:17,304 DEBUG   SenderThread:8512 [sender.py:send():379] send: header
2024-05-29 17:57:17,362 DEBUG   SenderThread:8512 [sender.py:send():379] send: run
2024-05-29 17:57:17,921 ERROR   SenderThread:8512 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-05-29 17:57:17,921 ERROR   SenderThread:8512 [internal_api.py:execute():374] {"errors":[{"message":"run zgh6omna was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-05-29 17:57:19,172 ERROR   SenderThread:8512 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-05-29 17:57:19,172 ERROR   SenderThread:8512 [internal_api.py:execute():374] {"errors":[{"message":"run zgh6omna was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-05-29 17:57:21,383 ERROR   SenderThread:8512 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-05-29 17:57:21,383 ERROR   SenderThread:8512 [internal_api.py:execute():374] {"errors":[{"message":"run zgh6omna was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-05-29 17:57:21,383 INFO    SenderThread:8512 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "C:\Users\lukea\anaconda3\envs\diss\Lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lukea\anaconda3\envs\diss\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 369, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lukea\anaconda3\envs\diss\Lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lukea\anaconda3\envs\diss\Lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lukea\anaconda3\envs\diss\Lib\site-packages\wandb\sdk\lib\gql_request.py", line 59, in execute
    request.raise_for_status()
  File "C:\Users\lukea\anaconda3\envs\diss\Lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql
2024-05-29 17:57:22,364 DEBUG   HandlerThread:8512 [handler.py:handle_request():146] handle_request: keepalive
2024-05-29 17:57:26,519 ERROR   SenderThread:8512 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-05-29 17:57:26,520 ERROR   SenderThread:8512 [internal_api.py:execute():374] {"errors":[{"message":"run zgh6omna was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-05-29 17:57:27,369 DEBUG   HandlerThread:8512 [handler.py:handle_request():146] handle_request: keepalive
2024-05-29 17:57:32,371 DEBUG   HandlerThread:8512 [handler.py:handle_request():146] handle_request: keepalive
2024-05-29 17:57:35,120 ERROR   SenderThread:8512 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-05-29 17:57:35,120 ERROR   SenderThread:8512 [internal_api.py:execute():374] {"errors":[{"message":"run zgh6omna was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-05-29 17:57:37,374 DEBUG   HandlerThread:8512 [handler.py:handle_request():146] handle_request: keepalive
2024-05-29 17:57:42,378 DEBUG   HandlerThread:8512 [handler.py:handle_request():146] handle_request: keepalive
2024-05-29 17:57:47,381 DEBUG   HandlerThread:8512 [handler.py:handle_request():146] handle_request: keepalive
2024-05-29 17:57:51,253 ERROR   SenderThread:8512 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-05-29 17:57:51,254 ERROR   SenderThread:8512 [internal_api.py:execute():374] {"errors":[{"message":"run zgh6omna was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-05-29 17:57:52,384 DEBUG   HandlerThread:8512 [handler.py:handle_request():146] handle_request: keepalive
2024-05-29 17:57:57,387 DEBUG   HandlerThread:8512 [handler.py:handle_request():146] handle_request: keepalive
2024-05-29 17:58:02,390 DEBUG   HandlerThread:8512 [handler.py:handle_request():146] handle_request: keepalive
2024-05-29 17:58:07,393 DEBUG   HandlerThread:8512 [handler.py:handle_request():146] handle_request: keepalive
2024-05-29 17:58:12,395 DEBUG   HandlerThread:8512 [handler.py:handle_request():146] handle_request: keepalive
2024-05-29 17:58:17,400 DEBUG   HandlerThread:8512 [handler.py:handle_request():146] handle_request: keepalive
2024-05-29 17:58:22,404 DEBUG   HandlerThread:8512 [handler.py:handle_request():146] handle_request: keepalive
2024-05-29 17:58:25,514 ERROR   SenderThread:8512 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-05-29 17:58:25,514 ERROR   SenderThread:8512 [internal_api.py:execute():374] {"errors":[{"message":"run zgh6omna was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-05-29 17:58:27,409 DEBUG   HandlerThread:8512 [handler.py:handle_request():146] handle_request: keepalive
2024-05-29 17:58:32,411 DEBUG   HandlerThread:8512 [handler.py:handle_request():146] handle_request: keepalive
2024-05-29 17:58:37,413 DEBUG   HandlerThread:8512 [handler.py:handle_request():146] handle_request: keepalive
2024-05-29 17:58:42,416 DEBUG   HandlerThread:8512 [handler.py:handle_request():146] handle_request: keepalive
2024-05-29 17:58:47,421 DEBUG   HandlerThread:8512 [handler.py:handle_request():146] handle_request: cancel
2024-05-29 17:58:47,422 DEBUG   HandlerThread:8512 [handler.py:handle_request():146] handle_request: cancel
2024-05-29 17:58:47,422 DEBUG   SenderThread:8512 [sender.py:send():388] Record cancelled: run
2024-05-29 17:58:47,424 DEBUG   HandlerThread:8512 [handler.py:handle_request():146] handle_request: status_report
2024-05-29 17:58:47,920 DEBUG   HandlerThread:8512 [handler.py:handle_request():146] handle_request: shutdown
2024-05-29 17:58:47,920 INFO    HandlerThread:8512 [handler.py:finish():866] shutting down handler
2024-05-29 17:58:48,424 INFO    SenderThread:8512 [sender.py:finish():1546] shutting down sender
2024-05-29 17:58:48,425 INFO    WriterThread:8512 [datastore.py:close():296] close: G:\My Drive\MSc\0_Project\MSc_Project\wandb\run-20240529_175717-zgh6omna\run-zgh6omna.wandb
