2024-05-29 17:57:16,412 INFO    StreamThr :31764 [internal.py:wandb_internal():86] W&B internal server running at pid: 31764, started at: 2024-05-29 17:57:16.408900
2024-05-29 17:57:16,416 DEBUG   HandlerThread:31764 [handler.py:handle_request():146] handle_request: status
2024-05-29 17:57:16,436 INFO    WriterThread:31764 [datastore.py:open_for_write():87] open: G:\My Drive\MSc\0_Project\MSc_Project\wandb\run-20240529_175716-pnn3n9n1\run-pnn3n9n1.wandb
2024-05-29 17:57:16,441 DEBUG   SenderThread:31764 [sender.py:send():379] send: header
2024-05-29 17:57:16,508 DEBUG   SenderThread:31764 [sender.py:send():379] send: run
2024-05-29 17:57:17,196 ERROR   SenderThread:31764 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-05-29 17:57:17,197 ERROR   SenderThread:31764 [internal_api.py:execute():374] {"errors":[{"message":"run pnn3n9n1 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-05-29 17:57:18,552 ERROR   SenderThread:31764 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-05-29 17:57:18,553 ERROR   SenderThread:31764 [internal_api.py:execute():374] {"errors":[{"message":"run pnn3n9n1 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-05-29 17:57:20,793 ERROR   SenderThread:31764 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-05-29 17:57:20,793 ERROR   SenderThread:31764 [internal_api.py:execute():374] {"errors":[{"message":"run pnn3n9n1 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-05-29 17:57:20,794 INFO    SenderThread:31764 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "C:\Users\lukea\anaconda3\envs\diss\Lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lukea\anaconda3\envs\diss\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 369, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lukea\anaconda3\envs\diss\Lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lukea\anaconda3\envs\diss\Lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lukea\anaconda3\envs\diss\Lib\site-packages\wandb\sdk\lib\gql_request.py", line 59, in execute
    request.raise_for_status()
  File "C:\Users\lukea\anaconda3\envs\diss\Lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql
2024-05-29 17:57:21,509 DEBUG   HandlerThread:31764 [handler.py:handle_request():146] handle_request: keepalive
2024-05-29 17:57:25,589 ERROR   SenderThread:31764 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-05-29 17:57:25,589 ERROR   SenderThread:31764 [internal_api.py:execute():374] {"errors":[{"message":"run pnn3n9n1 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-05-29 17:57:26,512 DEBUG   HandlerThread:31764 [handler.py:handle_request():146] handle_request: keepalive
2024-05-29 17:57:31,514 DEBUG   HandlerThread:31764 [handler.py:handle_request():146] handle_request: keepalive
2024-05-29 17:57:35,695 ERROR   SenderThread:31764 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-05-29 17:57:35,696 ERROR   SenderThread:31764 [internal_api.py:execute():374] {"errors":[{"message":"run pnn3n9n1 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-05-29 17:57:36,517 DEBUG   HandlerThread:31764 [handler.py:handle_request():146] handle_request: keepalive
2024-05-29 17:57:41,519 DEBUG   HandlerThread:31764 [handler.py:handle_request():146] handle_request: keepalive
2024-05-29 17:57:46,524 DEBUG   HandlerThread:31764 [handler.py:handle_request():146] handle_request: keepalive
2024-05-29 17:57:51,526 DEBUG   HandlerThread:31764 [handler.py:handle_request():146] handle_request: keepalive
2024-05-29 17:57:52,932 ERROR   SenderThread:31764 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-05-29 17:57:52,933 ERROR   SenderThread:31764 [internal_api.py:execute():374] {"errors":[{"message":"run pnn3n9n1 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-05-29 17:57:56,528 DEBUG   HandlerThread:31764 [handler.py:handle_request():146] handle_request: keepalive
2024-05-29 17:58:01,531 DEBUG   HandlerThread:31764 [handler.py:handle_request():146] handle_request: keepalive
2024-05-29 17:58:06,535 DEBUG   HandlerThread:31764 [handler.py:handle_request():146] handle_request: keepalive
2024-05-29 17:58:11,538 DEBUG   HandlerThread:31764 [handler.py:handle_request():146] handle_request: keepalive
2024-05-29 17:58:16,540 DEBUG   HandlerThread:31764 [handler.py:handle_request():146] handle_request: keepalive
2024-05-29 17:58:21,545 DEBUG   HandlerThread:31764 [handler.py:handle_request():146] handle_request: keepalive
2024-05-29 17:58:26,549 DEBUG   HandlerThread:31764 [handler.py:handle_request():146] handle_request: keepalive
2024-05-29 17:58:31,198 ERROR   SenderThread:31764 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-05-29 17:58:31,198 ERROR   SenderThread:31764 [internal_api.py:execute():374] {"errors":[{"message":"run pnn3n9n1 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-05-29 17:58:31,551 DEBUG   HandlerThread:31764 [handler.py:handle_request():146] handle_request: keepalive
2024-05-29 17:58:36,553 DEBUG   HandlerThread:31764 [handler.py:handle_request():146] handle_request: keepalive
2024-05-29 17:58:41,555 DEBUG   HandlerThread:31764 [handler.py:handle_request():146] handle_request: keepalive
2024-05-29 17:58:46,557 DEBUG   HandlerThread:31764 [handler.py:handle_request():146] handle_request: cancel
2024-05-29 17:58:46,558 DEBUG   HandlerThread:31764 [handler.py:handle_request():146] handle_request: cancel
2024-05-29 17:58:46,558 DEBUG   SenderThread:31764 [sender.py:send():388] Record cancelled: run
2024-05-29 17:58:46,558 DEBUG   HandlerThread:31764 [handler.py:handle_request():146] handle_request: status_report
2024-05-29 17:58:46,885 DEBUG   HandlerThread:31764 [handler.py:handle_request():146] handle_request: shutdown
2024-05-29 17:58:46,885 INFO    HandlerThread:31764 [handler.py:finish():866] shutting down handler
2024-05-29 17:58:47,559 INFO    SenderThread:31764 [sender.py:finish():1546] shutting down sender
2024-05-29 17:58:47,559 INFO    WriterThread:31764 [datastore.py:close():296] close: G:\My Drive\MSc\0_Project\MSc_Project\wandb\run-20240529_175716-pnn3n9n1\run-pnn3n9n1.wandb
